apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-iixnvkpb
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-iixnvkpb:bf4546a1b00e2c2637835e8b888db8560f7de720@sha256:6186756b800dac92675fb63a85a6566dcb9be8fac2defc8386b0bb91068ac42e
          name: container-image
